name: Publish new Release
on:
  workflow_dispatch:
jobs:
  publish:
    name: Sync Retype and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Update and Release
        shell: bash
        run: .github/workflows/refresh-release.sh --github-token="${{ secrets.GITHUB_TOKEN }}"
